//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINSAL_Admin.UnidadesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/minsal-admin-service/", ConfigurationName="UnidadesService.UnidadesServiceSoap")]
    public interface UnidadesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/getDumpUnidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MINSAL_Admin.UnidadesService.UnidadOrganizacional getDumpUnidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/getDumpUnidad", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<MINSAL_Admin.UnidadesService.UnidadOrganizacional> getDumpUnidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/recuperarUnidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string recuperarUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/recuperarUnidades", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> recuperarUnidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/recuperarUnidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string recuperarUnidad(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/recuperarUnidad", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> recuperarUnidadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/crearUnidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string crearUnidad(string nombre, string direccion, bool transporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/crearUnidad", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> crearUnidadAsync(string nombre, string direccion, bool transporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/asignarPadre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string asignarPadre(int id, int id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/asignarPadre", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> asignarPadreAsync(int id, int id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/asignarActiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string asignarActiva(int id, bool activa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/minsal-admin-service/asignarActiva", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> asignarActivaAsync(int id, bool activa);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost/minsal-admin-service/")]
    public partial class UnidadOrganizacional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_unidad_organizacionalField;
        
        private int unidad_padreField;
        
        private string nombreField;
        
        private string departamentoField;
        
        private bool activaField;
        
        private bool tiene_transporteField;
        
        private UnidadOrganizacional padreField;
        
        private UnidadOrganizacional[] hijosField;
        
        /// <comentarios/>
        public int id_unidad_organizacional {
            get {
                return this.id_unidad_organizacionalField;
            }
            set {
                this.id_unidad_organizacionalField = value;
                this.RaisePropertyChanged("id_unidad_organizacional");
            }
        }
        
        /// <comentarios/>
        public int unidad_padre {
            get {
                return this.unidad_padreField;
            }
            set {
                this.unidad_padreField = value;
                this.RaisePropertyChanged("unidad_padre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <comentarios/>
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <comentarios/>
        public bool tiene_transporte {
            get {
                return this.tiene_transporteField;
            }
            set {
                this.tiene_transporteField = value;
                this.RaisePropertyChanged("tiene_transporte");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadOrganizacional padre {
            get {
                return this.padreField;
            }
            set {
                this.padreField = value;
                this.RaisePropertyChanged("padre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadOrganizacional[] hijos {
            get {
                return this.hijosField;
            }
            set {
                this.hijosField = value;
                this.RaisePropertyChanged("hijos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UnidadesServiceSoapChannel : MINSAL_Admin.UnidadesService.UnidadesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnidadesServiceSoapClient : System.ServiceModel.ClientBase<MINSAL_Admin.UnidadesService.UnidadesServiceSoap>, MINSAL_Admin.UnidadesService.UnidadesServiceSoap {
        
        public UnidadesServiceSoapClient() {
        }
        
        public UnidadesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnidadesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MINSAL_Admin.UnidadesService.UnidadOrganizacional getDumpUnidad() {
            return base.Channel.getDumpUnidad();
        }
        
        public System.Threading.Tasks.Task<MINSAL_Admin.UnidadesService.UnidadOrganizacional> getDumpUnidadAsync() {
            return base.Channel.getDumpUnidadAsync();
        }
        
        public string recuperarUnidades() {
            return base.Channel.recuperarUnidades();
        }
        
        public System.Threading.Tasks.Task<string> recuperarUnidadesAsync() {
            return base.Channel.recuperarUnidadesAsync();
        }
        
        public string recuperarUnidad(int id) {
            return base.Channel.recuperarUnidad(id);
        }
        
        public System.Threading.Tasks.Task<string> recuperarUnidadAsync(int id) {
            return base.Channel.recuperarUnidadAsync(id);
        }
        
        public string crearUnidad(string nombre, string direccion, bool transporte) {
            return base.Channel.crearUnidad(nombre, direccion, transporte);
        }
        
        public System.Threading.Tasks.Task<string> crearUnidadAsync(string nombre, string direccion, bool transporte) {
            return base.Channel.crearUnidadAsync(nombre, direccion, transporte);
        }
        
        public string asignarPadre(int id, int id_padre) {
            return base.Channel.asignarPadre(id, id_padre);
        }
        
        public System.Threading.Tasks.Task<string> asignarPadreAsync(int id, int id_padre) {
            return base.Channel.asignarPadreAsync(id, id_padre);
        }
        
        public string asignarActiva(int id, bool activa) {
            return base.Channel.asignarActiva(id, activa);
        }
        
        public System.Threading.Tasks.Task<string> asignarActivaAsync(int id, bool activa) {
            return base.Channel.asignarActivaAsync(id, activa);
        }
    }
}
